# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configures rsyslog-ng for LogDNA on Ubuntu
# Used for educational purposes

Vagrant.configure("2") do |config|
  # ubuntu 18 LTS
  # config.vm.box = "ubuntu/bionic64"

  # ubuntu 20.04
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |v|
    v.name = "vagrant_ubuntu20_rsyslogng_logdna_server"
  end
  config.vm.network "public_network", ip: "192.168.0.122"

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant
    
    add-apt-repository ppa:adiscon/v8-devel
    apt-get update
    apt-get upgrade -y

    apt-get -y install rsyslog 

    mkdir -p /usr/local/share/ca-certificates/
    pushd /usr/local/share/ca-certificates/
        wget https://assets.logdna.com/rootca/ld-root-ca.crt
    popd
  SHELL

  # Uncomment for TCP+TLS (Suggested for security)
  config.vm.provision "file", source: "./configs/logdna-rsyslog-tcptls.conf", destination: "/tmp/logdna-syslog-ng.conf"

  # Uncomment for TCP (no TLS)
  #config.vm.provision "file", source: "./configs/logdna-rsyslog-tcp.conf", destination: "/tmp/logdna-syslog-ng.conf"

  # Uncomment for UDP (no TLS)
  # You must ask LogDNA Support to provision the syslog UDP port
  #config.vm.provision "file", source: "./configs/logdna-rsyslog-udp.conf", destination: "/tmp/logdna-syslog-ng.conf"

  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant

    cp /tmp/logdna-syslog-ng.conf /etc/syslog-ng/conf.d/logdna.conf
    systemctl start syslog-ng
  SHELL

end
